name: pangram
version: 1.4.1.10

dependencies:
  - base

library:
  exposed-modules: Pangram
  source-dirs: src
  ghc-options: -Wall
  dependencies:
      - unordered-containers
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
